steps:
  # step 1 build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
      - '.'
  # step 2 push the docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
  # Step 3: Deploy the newly built image to Cloud Run (FIXED PATH AND IMAGE NAME)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
  # Create Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'deploy', 'releases', 'create', 'release-${COMMIT_SHA}',
      '--delivery-pipeline=mytest',
      '--region=us-central1',
      '--images=myservice=us-central1-docker.pkg.dev/project-id/senthilmsbk/cloudtest/pipe-firstsample:${COMMIT_SHA}'
    ]
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
