steps:
  # step 1 build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
      - '.'
  # step 2 push the docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
  # Step 3: Deploy the newly built image to Cloud Run (FIXED PATH AND IMAGE NAME)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
  # Step 4:Create Cloud Deploy pipeline release
  - name : 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
      - -xe
      - -c
      - |
        gloud deploy apply --file=cloudtestpipeline.yml --region=us-central1
        gcloud deploy apply --file=cloudtesttarget.yml --region=us-central1
        gcloud deploy release create release-first-service-${COMMIT_SHA} \
          --delivery-pipeline=myservice-pipeline \
          --region=us-central1 \
          --release-config=devrelease.yml \
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/senthilmsbk/cloudtest/pipe-firstsample:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
