apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: "Target for dev environment"
run:
  location: projects/project-c2a841a1-54e5-42c1-823/locations/us-central1/services/cloudtestdev

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stage
description: "Target for stage environment"
run:
  location: projects/project-c2a841a1-54e5-42c1-823/locations/us-central1/services/cloudteststage
